name: Abcall CI

on:
  workflow_dispatch:
  push:
    branches: [ master, develop, 'feature/**', 'release/**', 'hotfix/**' ]
  pull_request:
    branches: [ master, develop, 'release/**' ]

jobs:
  ci:
    name: abcall ci
    runs-on: ubuntu-latest
        
    steps:
    - name: checkout de repositorio
      uses: actions/checkout@v4

    - name: Use Node.js 20.17.0
      uses: actions/setup-node@v4
      with:
        node-version: '20.17.0'
        cache: 'npm'
        
    - name: instalación de dependencias
      run: npm ci

    - name: Linter y Formateo
      run: npm run lint

    - name: Build
      run: npm run build --if-present

    - name: correr coverage unit test
      run: npm run test:pipeline
