name: Abcall CI

on:
  workflow_dispatch:
  push:
    branches: [ master, develop, 'feature/**', 'release/**', 'hotfix/**' ]
  pull_request:
    branches: [ master, develop, 'release/**' ]

jobs:
  abcall-ci:
    name: abcall-ci
    runs-on: ubuntu-latest

    steps:
    - name: repository checkout
      uses: actions/checkout@v4

    - name: Use Node.js 20.17.0
      uses: actions/setup-node@v4
      with:
        node-version: '20.17.0'
        cache: 'npm'

    - name: npm install --legacy-peer-deps
      run: npm ci --legacy-peer-deps

    - name: Lint
      run: npm run lint

    - name: Unit tests
      run: npm run test:pipeline

    - name: Build
      run: npm run build --if-present

  feature-to-develop:
    name: feature to develop
    if: contains(github.event.head_commit.message, 'to-develop') && (contains(github.ref, 'feature') || contains(github.ref, 'hotfix'))
    runs-on: ubuntu-latest
    needs: [abcall-ci]

    steps:
    - name: repository checkout
      uses: actions/checkout@v4

    - name: Use Node.js 20.17.0
      uses: actions/setup-node@v4
      with:
        node-version: '20.17.0'
        cache: 'npm'

    - name: npm install
      run: npm ci

    - name: develop to feature
      id: 'dev-to-feat'
      uses: tukasz/direct-merge-action@master
      continue-on-error: true
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: develop
        target-branch: ${{ github.ref }}

    - name: Are there conflicts?
      if: steps.dev-to-feat.outcome != 'success'
      run: |
        echo "There are probably conflicts with the develop branch or your branch is not up to date with develop, please integrate develop into your feature branch manually and do the push again"
        exit 1

    - name: Unit tests
      run: npm run test:pipeline

    - name: Build
      run: npm run build --if-present

    - name: feature to develop
      if: ${{ job.status=='success' }}
      uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: ${{ github.ref }}
        target-branch: develop

